version: "3.9"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./logs/mediamtx:/var/log/mediamtx
    ports:
      - "8554:8554"   # RTSP input
      - "8888:8888"   # HLS output

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-hls
    restart: unless-stopped
    volumes:
      - ./stream:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #  entrypoint: /bin/sh