services:
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./stream:/out
    ports:
      - "8554:8554"      # RTSP
    command: mediamtx /mediamtx.yml

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./stream:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

    restart: unless-stopped
