version: "3.9"

services:
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    ports:
      - "8888:8888"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./stream:/out
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-hls
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./stream:/usr/share/nginx/html
    ports:
      - "8080:80"
    restart: unless-stopped

  placeholder:
    image: busybox
    command: >
      sh -c '
        sleep 5 &&
        mkdir -p /stream/cam &&
        echo "#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-ENDLIST" > /stream/cam/index.m3u8
      '
    volumes:
      - ./stream:/stream
    restart: "no"